FROM golang:1.9

ENV BINARY pace

ARG APPLICATION
ARG PROJECT
ARG SERVER_ADDRESS
ARG DB_CONN

ENV APPLICATION ${APPLICATION}
ENV PROJECT ${PROJECT}
ENV SERVER_ADDRESS ${SERVER_ADDRESS}
ENV DB_CONN ${DB_CONN}

WORKDIR $GOPATH
COPY . src/github.com/242617/pace

RUN go get ./...
RUN go build \
    -o ${BINARY} \
    ${PROJECT}/cmd/${APPLICATION}

CMD ["sh", "-c", "$BINARY"]